"""
Cloud Functions (Gen 2) entry point for Enterprise Image Analyzer.

The Functions Framework expects a function as the entry point. This module
provides the 'app' function that handles HTTP requests by delegating to
the underlying Flask WSGI application.
"""

import os
from src.enterprise_app import enterprise_app


def app(request):
    """HTTP Cloud Function entry point.

    This function serves as the entry point for Google Cloud Functions.
    It receives HTTP requests and delegates them to the Flask application.

    Args:
        request (flask.Request): HTTP request object from Functions Framework.

    Returns:
        A Flask/Werkzeug Response object.
    """
    from werkzeug.wrappers import Response
    return Response.from_app(enterprise_app, request.environ)


def main(request):
    """Alternative HTTP Cloud Function entry point.

    Args:
        request (flask.Request): Incoming request object from Functions Framework.

    Returns:
        A Flask/Werkzeug Response generated by the Flask app for this request.
    """
    # Use Werkzeug helper to run the WSGI app against the incoming request environ
    from werkzeug.wrappers import Response
    return Response.from_app(enterprise_app, request.environ)


# For local testing (runs the Flask app directly)
if __name__ == '__main__':
    port = int(os.environ.get('PORT', 8080))
    enterprise_app.run(host='0.0.0.0', port=port, debug=False, threaded=True)
